### ISSUE TITLE
Passing function name in ColModel array

### ISSUE THREAD

**Issue by userfriendly** [michelpa/JqGridBundle#3]
I would like to pass a formatter function name in the colmodel options array, in order to have a cell display a specific icon instead of the numeric value passed, but it ends up as a quoted string (and hence isn't interpreted as a function reference in the rendered JS). Any other idea how I would go about this?

**Comment by userfriendly** [comment]
I reckon the problem is with how json_encode ignores JSON expressions, meaning this is the piece of code where I would need to start:

``` PHP
$response->setContent(json_encode($this->getData()));
```

One solution would be to use the JSON encoder of the Zend Framework, but that would add a nasty dependency. :-/

http://framework.zend.com/manual/en/zend.json.advanced.html#zend.json.advanced.expr

**Comment by michelpa** [comment]
you are right, there is an issue with quoted string. This is why i use "  $dp = ' ,"searchoptions" : {dataInit : datePick, "attr" : { "title": "Choisir une date" }}';" in column.php to handle the datePick function. As a workaround, you can use the action column at the moment and make a twig formatter for your data...

**Comment by michelpa** [comment]
Hello can you give a try now? You must specify the word "function" in your formatter: 
"formatter"=>'function(){alert('ttt');}'

**Comment by userfriendly** [comment]
Thanks mate. I'm using this bundle in a private project and am pretty busy with a work project at the moment, but I'll give it a try over the weekend. :) Cheers!
