### ISSUE TITLE
How to generate a CRUD ?

### ISSUE THREAD

**Issue by rafiimili** [michelpa/JqGridBundle#4]
I am trying this bundle in my application but i want to know if it's possible to generate a CRUD and how ?  

Thanks.

**Comment by michelpa** [comment]
I'm sorry but i don't understand your question... BTW, it's just a
datagrid, if you want to manage forms, you can do so by using action
column...

Pascal

2012/5/16 rafiimili <
reply@reply.github.com

**Comment by rafiimili** [comment]
I want to generate full add/edit/delete in my grid using jqgrid.
( you can see example here  [->New in version 3.7> Add/edit/delete on local data]: 
http://www.trirand.com/blog/jqgrid/jqgrid.html ). 
Actually,  i am using JqGridBundle just to show data and i want to generate  add/edit/delete fonctionalities.
I want to know if i can do that using this bundle .

Thanks

**Comment by michelpa** [comment]
It's not yet implemented...

Pascal

2012/5/16 rafiimili <
reply@reply.github.com

**Comment by rafiimili** [comment]
Thanks to precision. I hope that the next version.
Can i add CRUD using action column ?

**Comment by michelpa** [comment]
With action you are totally free to implement whatever you want, it's pure
symfony...

2012/5/16 rafiimili <
reply@reply.github.com

**Comment by rafiimili** [comment]
Thanks for your help. I will try action column .

**Comment by rafiimili** [comment]
Thanks.
